apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: deletetask-todo-deployment
spec:
  replicas: 1
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - deletetask-todo-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: deletetask-todo-deployment
      name: deletetask-todo-pod
    spec:
      containers:
      - name: deletetask-todo-container
        env:
        - name: CONNECTION_STRING 
          value: Driver={ODBC Driver 17 for SQL Server};Server=tcp:mehul-db.database.windows.net,1433;Database=todo;Uid=mehuladmin;Pwd=ME@open#321;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
        image: mehul005a/deletetasks-todo:latest
        ports:
        - containerPort: 8000
