apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: todoui-deployment
spec:
  replicas: 1
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - todoui-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: todoui-deployment
      name: todoui-pod
    spec:
      containers:
      - name: todoui-container
        # resources: 
        #     limits:
        #       memory: 200Mi
        #       cpu: 200Mi
        env:
        - name: CONNECTION_STRING 
          value: Driver={ODBC Driver 17 for SQL Server};Server=tcp:mehul-db.database.windows.net,1433;Database=todo;Uid=mehuladmin;Pwd=ME@open#321;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
        image: mehul005a/microui-todo:latest
        ports:
        - containerPort: 80
          hostPort: 8080
